version: '2'
networks:
  local:
    driver: bridge
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    networks:
      - local
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dev_qsdd
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:management
    ports:
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
